### ISSUE TITLE
Trần Huy Phượng Nhóm 1 thắc mắc và góp ý

### ISSUE THREAD

**Issue by nomiku1999** [superman19993/LTSSUD_1712718_1712683_1712584#3]
1. Trong phần mô tả ứng dụng mình nghĩ nhóm bạn nên nói kĩ hơn về việc sẽ song song hóa phần nào trong ứng dụng. Theo mình nhớ lần trước các bạn chọn song song hóa FPN, nhưng mình vẫn không biết được bạn song song hóa phần nào trong mạng FPN.
2. Không biết nhóm bạn đã code tuần tự chưa vì mình chỉ thấy 1 đoạn code tuần tự resize2. Nếu code rồi thì mong nhóm sớm update lên github để mình tham khảo.

**Comment by superman19993** [comment]
1. nhóm mình sẽ song song 1 phần liên quan đến quá trình bottom up của việc xây dựng FPN.
2. nhóm mình đã code tuần tự và song song (phiên bản 1) cho 2 hàm Zeropadding và Conv2D, bạn có thể tham khảo trong file inference3.py và parallel1.py.

Cảm ơn bạn đã đặt câu hỏi 👯‍♂️
